## Deploiement underlaying infrastructure 
# https://github.com/kubernetes-sigs/cluster-api-provider-gcp/blob/main/config/crd/bases/infrastructure.cluster.x-k8s.io_gcpclustertemplates.yaml 
##############################################
apiVersion: v1
kind: Namespace
metadata:
  name: capg-management-clusterclass

---

apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: GCPClusterTemplate
metadata:
  name: capg-uderlying-infrastructure
  namespace: capg-management-clusterclass
spec:
  template:
    spec:
      credentialsRef:
        name: gcp-credentials-v2
        namespace: default
      project: capg
      region: us-central1
      network:
        name: vpc-capg
        autoCreateSubnetworks: false
        hostProject: capg
        subnets:
          - name: snet-control-plan
            cidrBlock: "172.24.0.0/24"
            region: us-central1
          - name: snet-worker
            cidrBlock: "172.24.0.1/24"

